Ecommerce_Project/urls.py
from django.contrib import admin
from django.urls import path
from Ecommerce_App import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_login/', views.admin_login_view, name="admin_login"),
    path('admin_dashboard/', views.admin_dashboard_view, name="admin_dashboard"),
    path('admin_login_process/', views.admin_login_process,
         name="admin_login_process"),
    path('admin_logout_process/', views.admin_logout_process,
         name="admin_logout_process"),
    # Categories
    path('category_list/', views.categories_list_view.as_view(), name="category_list"),
    path('category_create/', views.category_create_view.as_view(),
         name="category_create"),
    path('category_update/<slug:pk>',
         views.category_update_view.as_view(), name="category_update"),
    # Subcategories
    path('sub_category_list/', views.sub_categories_list_view.as_view(),
         name="sub_category_list"),
    path('sub_category_create/', views.sub_category_create_view.as_view(),
         name="sub_category_create"),
    path('sub_category_update/<slug:pk>',
         views.sub_category_update_view.as_view(), name="sub_category_update"),
    # Merchants
    path('merchant_create/', views.merchant_user_create_view.as_view(),
         name="merchant_create"),
    path('merchant_list/', views.merchant_user_list_view.as_view(),
         name="merchant_list"),
    path('merchant_update/<slug:pk>', views.merchant_user_update_view.as_view(),
         name="merchant_update"),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce_App/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse
# Create your models here.


class CustomUser(AbstractUser):
    user_type_choices = ((1, " Admin"), (2, "Staff"),
                         (3, "Merchant"), (4, "Customer"))
    user_type = models.IntegerField(choices=user_type_choices, default=1)


class AdminUser(models.Model):
    profile_pic = models.FileField(default="")
    auth_user_id = models.OneToOneField(
        CustomUser, related_name="adminuser", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class StaffUser(models.Model):
    profile_pic = models.FileField(default="")
    auth_user_id = models.OneToOneField(
        CustomUser, related_name="staffuser", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class MerchantUser(models.Model):
    profile_pic = models.FileField(default="")
    auth_user_id = models.OneToOneField(
        CustomUser, related_name="merchantuser", on_delete=models.CASCADE)
    company_name = models.CharField(max_length=255)
    gst_details = models.CharField(max_length=255)
    address = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.auth_user_id.first_name} {self.auth_user_id.last_name}"


class CustomerUser(models.Model):
    profile_pic = models.FileField(default="")
    auth_user_id = models.OneToOneField(
        CustomUser, related_name="customeruser", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Categories(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    url_slug = models.CharField(max_length=255)
    thumbnail = models.FileField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)

    def get_absolute_url(self):
        return reverse("category_list")

    def __str__(self):
        return self.title


class SubCategories(models.Model):
    id = models.AutoField(primary_key=True)
    cathegory_id = models.ForeignKey(Categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    url_slug = models.CharField(max_length=255)
    thumbnail = models.FileField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)

    def get_absolute_url(self):
        return reverse("sub_category_list")


class Products(models.Model):
    id = models.AutoField(primary_key=True)
    url_slug = models.CharField(max_length=255)
    subcategories_id = models.ForeignKey(
        SubCategories, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=255)
    brand = models.CharField(max_length=255)
    product_max_price = models.CharField(max_length=255)
    product_discount_price = models.CharField(max_length=255)
    product_description = models.TextField()
    product_long_discription = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    added_by_merchant = models.ForeignKey(
        MerchantUser, on_delete=models.CASCADE)
    in_stock_total = models.IntegerField(default=1)
    is_active = models.IntegerField(default=1)


class ProductMedia(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    media_type_choice = ((1, "Image"), (2, "Video"))
    media_type = models.CharField(max_length=255)
    media_content = models.FileField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductTransaction(models.Model):
    id = models.AutoField(primary_key=True)
    transaction_type_choices = ((1, "BUY"), (2, "SELL"))
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    transaction_product_count = models.IntegerField(default=1)
    transaction_type = models.CharField(
        choices=transaction_type_choices, max_length=255)
    transaction_description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class ProductDetails(models.CharField):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    title_details = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductAbout(models.CharField):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductTag(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductQuestions(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.TextField()
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductReviews(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    user_id = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    review_image = models.FileField()
    rating = models.CharField(default="5", max_length=255)
    review = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductReviewVoting(models.Model):
    id = models.AutoField(primary_key=True)
    product_review_id = models.ForeignKey(
        ProductReviews, on_delete=models.CASCADE)
    user_id_voting = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductVarient(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class ProductVarientItems(models.Model):
    id = models.AutoField(primary_key=True)
    product_vareint_id = models.ForeignKey(
        ProductVarient, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class CustomerOrder(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.DO_NOTHING)
    purchase_price = models.CharField(max_length=255)
    coupon_code = models.CharField(max_length=255)
    discount_amount = models.CharField(max_length=255)
    product_status = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class OrderDeliveryStatus(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey(CustomerOrder, on_delete=models.CASCADE)
    status = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            AdminUser.objects.create(auth_user_id=instance)
        if instance.user_type == 2:
            StaffUser.objects.create(auth_user_id=instance)
        if instance.user_type == 3:
            MerchantUser.objects.create(auth_user_id=instance,
                                        company_name="", gst_details="", address="")
        if instance.user_type == 4:
            CustomerUser.objects.create(auth_user_id=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.adminuser.save()
    if instance.user_type == 2:
        instance.staffuser.save()
    if instance.user_type == 3:
        instance.merchantuser.save()
    if instance.user_type == 4:
        instance.customeruser.save()

Ecommerce_App/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from . import models
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
# Create your views here.


def admin_login_view(request):
    return render(request, "admin_template/admin_login.html", {})


def admin_logout_process(request):
    logout(request)
    messages.success(request, "Logout Successfully")
    return HttpResponseRedirect(reverse('admin_login'))


@login_required(login_url="/admin_login/")
def admin_dashboard_view(request):
    return render(request, "admin_template/admin_dashboard.html")


def admin_login_process(request):
    username = request.POST.get("username")
    password = request.POST.get("password")

    user = authenticate(request=request, username=username, password=password)
    if user is not None:
        login(request=request, user=user)
        return HttpResponseRedirect(reverse("admin_dashboard"))
    else:
        messages.error(request, "Error in Login! Invalid Login Details!")
        return HttpResponseRedirect(reverse("admin_login"))

# Category Views


class categories_list_view(ListView):
    model = models.Categories
    template_name = "admin_template/category_list.html"
    paginate_by = 4

    def get_queryset(self):
        filter_val = self.request.GET.get("filter", "")
        order_by = self.request.GET.get("orderby", "id")
        if filter_val != "":
            cat = models.Categories.objects.filter(Q(title__contains=filter_val) | Q(
                description__contains=filter_val)).order_by(order_by)
        else:
            cat = models.Categories.objects.all().order_by(order_by)
        return cat

    def get_context_data(self, **kwargs):
        context = super(categories_list_view, self).get_context_data(**kwargs)
        context["filter"] = self.request.GET.get("filter", "")
        context["orderby"] = self.request.GET.get("orderby", "id")
        context["all_table_fields"] = models.Categories._meta.get_fields()
        return context


class category_create_view(SuccessMessageMixin, CreateView):
    model = models.Categories
    success_message = "Category added successfully!!!"
    fields = "__all__"
    template_name = "admin_template/category_create.html"


class category_update_view(SuccessMessageMixin, UpdateView):
    model = models.Categories
    success_message = "Category Updated successfully!!!"
    fields = "__all__"
    template_name = "admin_template/category_update.html"

# Subcategory Views


class sub_categories_list_view(ListView):
    model = models.SubCategories
    template_name = "admin_template/subcategory_list.html"
    paginate_by = 4

    def get_queryset(self):
        filter_val = self.request.GET.get("filter", "")
        order_by = self.request.GET.get("orderby", "id")
        if filter_val != "":
            cat = models.SubCategories.objects.filter(Q(title__contains=filter_val) | Q(
                description__contains=filter_val)).order_by(order_by)
        else:
            cat = models.SubCategories.objects.all().order_by(order_by)
        return cat

    def get_context_data(self, **kwargs):
        context = super(sub_categories_list_view,
                        self).get_context_data(**kwargs)
        context["filter"] = self.request.GET.get("filter", "")
        context["orderby"] = self.request.GET.get("orderby", "id")
        context["all_table_fields"] = models.SubCategories._meta.get_fields()
        return context


class sub_category_create_view(SuccessMessageMixin, CreateView):
    model = models.SubCategories
    success_message = "Sub Category added successfully!!!"
    fields = "__all__"
    template_name = "admin_template/subcategory_create.html"


class sub_category_update_view(SuccessMessageMixin, UpdateView):
    model = models.SubCategories
    success_message = "Sub Category Updated successfully!!!"
    fields = "__all__"
    template_name = "admin_template/subcategory_update.html"


class merchant_user_create_view(SuccessMessageMixin, CreateView):
    template_name = "admin_template/merchant_create.html"
    model = models.CustomUser
    fields = ["first_name", "last_name", "email", "username", "password"]

    def form_valid(self, form):
        # saving Custom user object for merchant user
        user = form.save(commit=False)
        user.is_active = True
        user.user_type = 3
        user.set_password(form.cleaned_data["password"])
        user.save()

        # saving merchant user
        profile_pic = self.request.FILES["profile_pic"]
        fs = FileSystemStorage()
        filename = fs.save(profile_pic.name, profile_pic)
        profile_pic_url = fs.url(filename)

        user.merchantuser.profile_pic = profile_pic_url
        user.merchantuser.company_name = self.request.POST.get("company_name")
        user.merchantuser.gst_details = self.request.POST.get("gst_details")
        user.merchantuser.address = self.request.POST.get("address")
        user.save()
        messages.success(self.request, "Merchant user Added successfully")
        return HttpResponseRedirect(reverse("merchant_list"))


class merchant_user_list_view(ListView):
    model = models.MerchantUser
    template_name = "admin_template/merchant_list.html"


class merchant_user_update_view(SuccessMessageMixin, UpdateView):
    model = models.CustomUser
    template_name = "admin_template/merchant_update.html"
    fields = ["first_name", "last_name", "email", "username", "password"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        model = models.MerchantUser.objects.get(auth_user_id=self.object.pk)
        context["merchantuser"] = model
        return context

    def form_valid(self, form):
        # saving Custom user object for merchant user
        user = form.save(commit=False)
        user.set_password(form.cleaned_data["password"])
        user.save()

        # saving merchant user update
        merchantuser = models.MerchantUser.objects.get(auth_user_id=user.id)
        if self.request.FILES.get("profile_pic", False):
            profile_pic = self.request.FILES["profile_pic"]
            fs = FileSystemStorage()
            filename = fs.save(profile_pic.name, profile_pic)
            profile_pic_url = fs.url(filename)
            merchantuser.profile_pic = profile_pic_url

        merchantuser.company_name = self.request.POST.get("company_name")
        merchantuser.gst_details = self.request.POST.get("gst_details")
        merchantuser.address = self.request.POST.get("address")
        merchantuser.save()
        messages.success(self.request, "Merchant user updated successfully")
        return HttpResponseRedirect(reverse("merchant_list"))

Ecommerce_App/templates/admin_template/admin_dashboard.html
  {% extends 'admin_template/base_template.html' %}
  {% block title %}
    Dashboard
  {% endblock title %}

  {% block page_title %}
    Dashboard
  {% endblock page_title %}

  {% block page_content %}
  <p>Simple Dashboard</p>
  {% endblock page_content %}

Ecommerce_App/templates/admin_template/category_create.html
{% extends 'admin_template/base_template.html' %}
{% block title %}
  Category Create
{% endblock title %}

{% block page_title %}
  Category Create
{% endblock page_title %}

{% block page_content %}
<div class="row">
    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
          <div class="card-header">
            <h4>Categorys</h4>
          </div>
          <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% for fields in form %}
                    <div class="form-group">
                        <label>{{fields.label}}</label>
                        <input type="{{fields.field.widget.input_type}}" name = "{{fields.name}}" class="form-control">
                    </div>
                {% endfor %}
                <button type = "submit">Save Category</button>
            </form>
          </div>
        </div>
    </div>
</div>

{% endblock page_content %}

Ecommerce_App/templates/admin_template/category_list.html
{% extends 'admin_template/base_template.html' %}
{% block title %}
  Category List
{% endblock title %}

{% block page_title %}
  Category List
{% endblock page_title %}

{% block page_content %}
  <div class="col-lg-12">
    <div class="search-element">
      <div class="card">
          <div class="card-body">
              <form action="" method="get">
                <div class="row">
                  <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="filter" data-width="250" style="float:left">
                  <button class="btn btn-primary" type="submit"><i class="fas fa-search">Search</i></button>
                </div>
              </form>
          </div> 
      </div>
    </div>
  </div>
  <div class="col-lg-12">
    <div class="search-element">
      <div class="card">
          <div class="card-body">
              <b>Sort by:</b>&nbsp;
              <a href="{% url 'category_list' %}?filter={{filter}}&orderby=id">Id</a>&nbsp;<b>|</b>&nbsp;
              <a href="{% url 'category_list' %}?filter={{filter}}&orderby=title"">Title</a>&nbsp;<b>|</b>&nbsp;
              <a href="{% url 'category_list' %}?filter={{filter}}&orderby=description"">Description</a>
          </div> 
      </div>
    </div>
  </div>
<div class="col-md-12">
  <div class="row">
{% for category in categories_list %}
<div class="col-12 col-sm-6 col-md-6 col-lg-3">
  <article class="article article-style-b">
    <div class="article-header">
      <div class="article-image" data-background="/media/{{category.thumbnail }}">
      </div>
        <div class="article-badge">
          <div class="article-badge-item bg-danger"><i class="fas fa-fire"></i>{{category.title}}</div>
          </div>
        </div>
        <div class="article-details">
            <p>{{category.description}}</p>
            <p><span class = "badge badge-primary">Url slug: {{category.url_slug}}</span></p>
          <div class="article-cta">
            <label class="custom-switch mt-2" style = "float:left">
              <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input" {% if category.is_active == 1 %} checked {% endif %} disabled>
              <span class="custom-switch-indicator"></span>
              <span class="custom-switch-description">Active</span>
            </label>
            <a href="{% url 'category_update' category.id %}" class = "btn btn-warning">Edit <i class="fas fa-chevron-right"></i></a>
          </div>
    </div>
  </article>
</div>
{% endfor %} 
</div>
</div>
<div class="row">
  <div class="col-lg-12">
<div class="card-body">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="{% url 'category_list' %}?filter={{filter}}&orderby={{orderby}}&page={{page_obj.previous_page_number}}">Previous</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="">Previous</a></li>
      {% endif %}
      {% for i in paginator.page_range %}
        <li class="page-item"><a class="page-link" href="{% url 'category_list' %}?filter={{filter}}&orderby={{orderby}}&page={{i}}">{{i}}</a></li>
      {% endfor %}
      {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="{% url 'category_list' %}?filter={{filter}}&orderby={{orderby}}&page={{page_obj.next_page_number}}">Next</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="">Next</a></li>
      {% endif %}
    </ul>
  </nav>
</div>
</div>
</div>
{% endblock page_content %}

Ecommerce_App/templates/admin_template/category_update.html
{% extends 'admin_template/base_template.html' %}
{% block title %}
  Category Update
{% endblock title %}

{% block page_title %}
  Category Update
{% endblock page_title %}

{% block page_content %}
<div class="row">
    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
          <div class="card-header">
            <h4>Categories</h4>
          </div>
          <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for fields in form %}
                    <div class="form-group"> 
                        {% if fields.errors %}
                            <div class="alert alert-danger">
                                {{fields.errors}}
                            </div>
                        {% endif %}
                        <label>{{fields.label}}</label>
                        <input value="{{fields.value}}" type="{{fields.field.widget.input_type}}" id = "{{fields.name}}" name = "{{fields.name}}" class="form-control">
                    </div>
                    {% if fields.field.widget.input_type == "file" %}
                        <div class="form-group">
                            <label for="">Current thumbnail : {{fields.value}}</label><br>
                            <div class="card">
                                <div class="card-body">
                                    <img class = "img-fluid" src="/media/{{fields.value}}" alt="">
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <button class = "btn btn-primary btn-block" type = "submit">Save Category</button>
            </form>
          </div>
        </div>
    </div>
</div>
<script>
    document.querySelector('#title').onkeyup=function(){
        let title = document.querySelector('#title').value;
        url = "";
        for(i=0; i<title.length; i++){
            if(title[i]==" "){
                url+="-";
            }
            else{
                url+=title[i];
            }
        }

        document.querySelector('#url_slug').value=url.toLowerCase();
    }
</script>
{% endblock page_content %}

Ecommerce_App/templates/admin_template/merchant_list.html
{% extends 'admin_template/base_template.html' %}
{% block title %}
  Merchant User List
{% endblock title %}

{% block page_title %}
Merchant User List
{% endblock page_title %}

{% block page_content %}
<div class="row">
{% for merchant in merchantuser_list %}
    <div class="col-12 col-sm-6 col-md-6 col-lg-3">
        <article class="article article-style-b">
          <div class="article-header">
            <div class="article-image" data-background="{{merchant.profile_pic}}" style="background-image: url(&quot;assets/img/news/img13.jpg&quot;);">
            </div>
            <div class="article-badge">
              <div class="article-badge-item bg-danger"><i class="fas fa-fire"></i>{{merchant.auth_user_id.username}}</div>
            </div>
          </div>
          <div class="article-details">
            <p><span class = "badge badge-primary">First Name: {{merchant.auth_user_id.first_name}}</span></p>
            <p><span class = "badge badge-primary">Last Name: {{merchant.auth_user_id.last_name}}</span></p>
            <p><span class = "badge badge-primary">Address: {{merchant.company_name}}</span></p>
            <p><span class = "badge badge-primary">GST: {{merchant.gst_details}}</span></p>
            <p><span class = "badge badge-primary">Company Name: {{merchant.company_name}}</span></p>
            <div class="article-cta">
                <label class="custom-switch mt-2" style = "float:left">
                    <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input" {% if merchant.auth_user_id.is_active == 1 %} checked {% endif %} disabled>
                    <span class="custom-switch-indicator"></span>
                    <span class="custom-switch-description">Active</span>
                </label>
              <a href="{% url 'merchant_update' merchant.auth_user_id.id %}" class = "btn btn-warning">Edit <i class="fas fa-chevron-right"></i></a>
            </div>
          </div>
        </article>
      </div>
{% endfor %} 
</div>
{% endblock page_content %}

Ecommerce_App/templates/admin_template/subcategory_list.html
{% extends 'admin_template/base_template.html' %}
{% block title %}
  Sub Category List
{% endblock title %}

{% block page_title %}
  Sub Category List
{% endblock page_title %}

{% block page_content %}
<div class="col-lg-12">
  <div class="search-element">
    <div class="card">
        <div class="card-body">
            <form action="" method="get">
              <div class="row">
                <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="filter" data-width="250" style="float:left">
                <button class="btn btn-primary" type="submit"><i class="fas fa-search">Search</i></button>
              </div>
            </form>
        </div> 
    </div>
  </div>
</div>
<div class="col-lg-12">
  <div class="search-element">
    <div class="card">
        <div class="card-body">
            <b>Sort by:</b>&nbsp;
            <a href="{% url 'category_list' %}?filter={{filter}}&orderby=id">Id</a>&nbsp;<b>|</b>&nbsp;
            <a href="{% url 'category_list' %}?filter={{filter}}&orderby=title"">Title</a>&nbsp;<b>|</b>&nbsp;
            <a href="{% url 'category_list' %}?filter={{filter}}&orderby=description"">Description</a>
        </div> 
    </div>
  </div>
</div>
<div class="row">
{% for subcategory in subcategories_list %}
    <div class="col-12 col-sm-6 col-md-6 col-lg-3">
        <article class="article article-style-b">
          <div class="article-header">
            <div class="article-image" data-background="/media/{{subcategory.thumbnail }}" style="background-image: url(&quot;assets/img/news/img13.jpg&quot;);">
            </div>
            <div class="article-badge">
              <div class="article-badge-item bg-danger"><i class="fas fa-fire"></i>{{category.title}}</div>
            </div>
          </div>
          <div class="article-details">
            <p><span class="badge badge-secondary">{{subcategory.cathegory_id.title}}</span></p>
            <p>{{subcategory.description}}</p>
            <p><span class = "badge badge-primary">Url slug: {{subcategory.url_slug}}</span></p>
            <div class="article-cta">
                <label class="custom-switch mt-2" style = "float:left">
                    <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input" {% if subcategory.is_active == 1 %} checked {% endif %} disabled>
                    <span class="custom-switch-indicator"></span>
                    <span class="custom-switch-description">Active</span>
                </label>
              <a href="{% url 'sub_category_update' subcategory.id %}" class = "btn btn-warning">Edit <i class="fas fa-chevron-right"></i></a>
            </div>
          </div>
        </article>
      </div>
{% endfor %} 
</div>
<div class="row">
  <div class="col-lg-12">
<div class="card-body">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="{% url 'sub_category_list' %}?filter={{filter}}&orderby={{orderby}}&page={{page_obj.previous_page_number}}">Previous</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="">Previous</a></li>
      {% endif %}
      {% for i in paginator.page_range %}
        <li class="page-item"><a class="page-link" href="{% url 'sub_category_list' %}?filter={{filter}}&orderby={{orderby}}&page={{i}}">{{i}}</a></li>
      {% endfor %}
      {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="{% url 'sub_category_list' %}?filter={{filter}}&orderby={{orderby}}&page={{page_obj.next_page_number}}">Next</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="">Next</a></li>
      {% endif %}
    </ul>
  </nav>
</div>
</div>
</div>
{% endblock page_content %}